# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: led_basestation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='led_basestation.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15led_basestation.proto\"L\n\x07\x46licker\x12\x0e\n\x06length\x18\x01 \x02(\r\x12\x0c\n\x04rate\x18\x02 \x02(\r\x12\x10\n\x08on_color\x18\x03 \x02(\r\x12\x11\n\toff_color\x18\x04 \x01(\r\"?\n\x04\x46\x61\x64\x65\x12\x0e\n\x06length\x18\x01 \x02(\r\x12\x12\n\ndest_color\x18\x02 \x02(\r\x12\x13\n\x0bstart_color\x18\x03 \x01(\r\"\x1e\n\x08SetColor\x12\x12\n\ndest_color\x18\x01 \x02(\r\"\xa4\x01\n\x07\x43ommand\x12\x0f\n\x07groupid\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\r\x12#\n\x0f\x66licker_command\x18\x03 \x01(\x0b\x32\x08.FlickerH\x00\x12\x1d\n\x0c\x66\x61\x64\x65_command\x18\x04 \x01(\x0b\x32\x05.FadeH\x00\x12&\n\x11set_color_command\x18\x05 \x01(\x0b\x32\t.SetColorH\x00\x42\t\n\x07payload')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLICKER = _descriptor.Descriptor(
  name='Flicker',
  full_name='Flicker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='Flicker.length', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='Flicker.rate', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_color', full_name='Flicker.on_color', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='off_color', full_name='Flicker.off_color', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=101,
)


_FADE = _descriptor.Descriptor(
  name='Fade',
  full_name='Fade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='Fade.length', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_color', full_name='Fade.dest_color', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_color', full_name='Fade.start_color', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=166,
)


_SETCOLOR = _descriptor.Descriptor(
  name='SetColor',
  full_name='SetColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest_color', full_name='SetColor.dest_color', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=198,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupid', full_name='Command.groupid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Command.timestamp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flicker_command', full_name='Command.flicker_command', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fade_command', full_name='Command.fade_command', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_color_command', full_name='Command.set_color_command', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='Command.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=201,
  serialized_end=365,
)

_COMMAND.fields_by_name['flicker_command'].message_type = _FLICKER
_COMMAND.fields_by_name['fade_command'].message_type = _FADE
_COMMAND.fields_by_name['set_color_command'].message_type = _SETCOLOR
_COMMAND.oneofs_by_name['payload'].fields.append(
  _COMMAND.fields_by_name['flicker_command'])
_COMMAND.fields_by_name['flicker_command'].containing_oneof = _COMMAND.oneofs_by_name['payload']
_COMMAND.oneofs_by_name['payload'].fields.append(
  _COMMAND.fields_by_name['fade_command'])
_COMMAND.fields_by_name['fade_command'].containing_oneof = _COMMAND.oneofs_by_name['payload']
_COMMAND.oneofs_by_name['payload'].fields.append(
  _COMMAND.fields_by_name['set_color_command'])
_COMMAND.fields_by_name['set_color_command'].containing_oneof = _COMMAND.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Flicker'] = _FLICKER
DESCRIPTOR.message_types_by_name['Fade'] = _FADE
DESCRIPTOR.message_types_by_name['SetColor'] = _SETCOLOR
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND

Flicker = _reflection.GeneratedProtocolMessageType('Flicker', (_message.Message,), dict(
  DESCRIPTOR = _FLICKER,
  __module__ = 'led_basestation_pb2'
  # @@protoc_insertion_point(class_scope:Flicker)
  ))
_sym_db.RegisterMessage(Flicker)

Fade = _reflection.GeneratedProtocolMessageType('Fade', (_message.Message,), dict(
  DESCRIPTOR = _FADE,
  __module__ = 'led_basestation_pb2'
  # @@protoc_insertion_point(class_scope:Fade)
  ))
_sym_db.RegisterMessage(Fade)

SetColor = _reflection.GeneratedProtocolMessageType('SetColor', (_message.Message,), dict(
  DESCRIPTOR = _SETCOLOR,
  __module__ = 'led_basestation_pb2'
  # @@protoc_insertion_point(class_scope:SetColor)
  ))
_sym_db.RegisterMessage(SetColor)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'led_basestation_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  ))
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
