/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Sun Sep 11 15:17:53 2016. */

#ifndef PB_LED_BASESTATION_PB_H_INCLUDED
#define PB_LED_BASESTATION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Fade {
    uint32_t length;
    uint32_t dest_color;
    bool has_start_color;
    uint32_t start_color;
/* @@protoc_insertion_point(struct:Fade) */
} Fade;

typedef struct _Flicker {
    uint32_t length;
    uint32_t rate;
    uint32_t on_color;
    bool has_off_color;
    uint32_t off_color;
/* @@protoc_insertion_point(struct:Flicker) */
} Flicker;

typedef struct _SetColor {
    uint32_t dest_color;
/* @@protoc_insertion_point(struct:SetColor) */
} SetColor;

typedef struct _Command {
    uint32_t groupid;
    uint32_t timestamp;
    pb_size_t which_payload;
    union {
        Flicker flicker_command;
        Fade fade_command;
        SetColor set_color_command;
    } payload;
/* @@protoc_insertion_point(struct:Command) */
} Command;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Flicker_init_default                     {0, 0, 0, false, 0}
#define Fade_init_default                        {0, 0, false, 0}
#define SetColor_init_default                    {0}
#define Command_init_default                     {0, 0, 0, {Flicker_init_default}}
#define Flicker_init_zero                        {0, 0, 0, false, 0}
#define Fade_init_zero                           {0, 0, false, 0}
#define SetColor_init_zero                       {0}
#define Command_init_zero                        {0, 0, 0, {Flicker_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Fade_length_tag                          1
#define Fade_dest_color_tag                      2
#define Fade_start_color_tag                     3
#define Flicker_length_tag                       1
#define Flicker_rate_tag                         2
#define Flicker_on_color_tag                     3
#define Flicker_off_color_tag                    4
#define SetColor_dest_color_tag                  1
#define Command_flicker_command_tag              3
#define Command_fade_command_tag                 4
#define Command_set_color_command_tag            5
#define Command_groupid_tag                      1
#define Command_timestamp_tag                    2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Flicker_fields[5];
extern const pb_field_t Fade_fields[4];
extern const pb_field_t SetColor_fields[2];
extern const pb_field_t Command_fields[6];

/* Maximum encoded size of messages (where known) */
#define Flicker_size                             24
#define Fade_size                                18
#define SetColor_size                            6
#define Command_size                             38

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LED_BASESTATION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
