/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Fri Jan 13 23:41:01 2017. */

#include "flicker_base_response.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FlickerBaseResponse_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, FlickerBaseResponse, err, err, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
