/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Sun Sep 11 22:07:26 2016. */

#include "flicker_base_message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Strobe_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Strobe, length, length, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Strobe, rate, length, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Strobe, on_color, rate, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, Strobe, off_color, on_color, 0),
    PB_LAST_FIELD
};

const pb_field_t Fade_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Fade, length, length, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Fade, dest_color, length, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Fade, start_color, dest_color, 0),
    PB_LAST_FIELD
};

const pb_field_t SetColor_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetColor, dest_color, dest_color, 0),
    PB_LAST_FIELD
};

const pb_field_t FlickerBaseMessage_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, FlickerBaseMessage, groupid, groupid, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, FlickerBaseMessage, timestamp, groupid, 0),
    PB_ONEOF_FIELD(payload,   3, MESSAGE , ONEOF, STATIC  , OTHER, FlickerBaseMessage, strobe, timestamp, &Strobe_fields),
    PB_ONEOF_FIELD(payload,   4, MESSAGE , ONEOF, STATIC  , OTHER, FlickerBaseMessage, fade, timestamp, &Fade_fields),
    PB_ONEOF_FIELD(payload,   5, MESSAGE , ONEOF, STATIC  , OTHER, FlickerBaseMessage, setColor, timestamp, &SetColor_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FlickerBaseMessage, payload.strobe) < 65536 && pb_membersize(FlickerBaseMessage, payload.fade) < 65536 && pb_membersize(FlickerBaseMessage, payload.setColor) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Strobe_Fade_SetColor_FlickerBaseMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FlickerBaseMessage, payload.strobe) < 256 && pb_membersize(FlickerBaseMessage, payload.fade) < 256 && pb_membersize(FlickerBaseMessage, payload.setColor) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Strobe_Fade_SetColor_FlickerBaseMessage)
#endif


/* @@protoc_insertion_point(eof) */
