# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flicker_base_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flicker_base_message.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x66licker_base_message.proto\"K\n\x06Strobe\x12\x0e\n\x06length\x18\r \x02(\r\x12\x0c\n\x04rate\x18\x0c \x02(\r\x12\x10\n\x08on_color\x18\x0b \x02(\r\x12\x11\n\toff_color\x18\n \x01(\r\"?\n\x04\x46\x61\x64\x65\x12\x0e\n\x06length\x18\t \x02(\r\x12\x12\n\ndest_color\x18\x08 \x02(\r\x12\x13\n\x0bstart_color\x18\x07 \x01(\r\"\x1e\n\x08SetColor\x12\x12\n\ndest_color\x18\x06 \x02(\r\"\x94\x01\n\x12\x46lickerBaseMessage\x12\x0f\n\x07groupid\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\r\x12\x19\n\x06strobe\x18\x03 \x01(\x0b\x32\x07.StrobeH\x00\x12\x15\n\x04\x66\x61\x64\x65\x18\x04 \x01(\x0b\x32\x05.FadeH\x00\x12\x1d\n\x08setColor\x18\x05 \x01(\x0b\x32\t.SetColorH\x00\x42\t\n\x07payload')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STROBE = _descriptor.Descriptor(
  name='Strobe',
  full_name='Strobe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='Strobe.length', index=0,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='Strobe.rate', index=1,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_color', full_name='Strobe.on_color', index=2,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='off_color', full_name='Strobe.off_color', index=3,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=105,
)


_FADE = _descriptor.Descriptor(
  name='Fade',
  full_name='Fade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='Fade.length', index=0,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_color', full_name='Fade.dest_color', index=1,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_color', full_name='Fade.start_color', index=2,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=170,
)


_SETCOLOR = _descriptor.Descriptor(
  name='SetColor',
  full_name='SetColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest_color', full_name='SetColor.dest_color', index=0,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=202,
)


_FLICKERBASEMESSAGE = _descriptor.Descriptor(
  name='FlickerBaseMessage',
  full_name='FlickerBaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupid', full_name='FlickerBaseMessage.groupid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FlickerBaseMessage.timestamp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strobe', full_name='FlickerBaseMessage.strobe', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fade', full_name='FlickerBaseMessage.fade', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setColor', full_name='FlickerBaseMessage.setColor', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='FlickerBaseMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=205,
  serialized_end=353,
)

_FLICKERBASEMESSAGE.fields_by_name['strobe'].message_type = _STROBE
_FLICKERBASEMESSAGE.fields_by_name['fade'].message_type = _FADE
_FLICKERBASEMESSAGE.fields_by_name['setColor'].message_type = _SETCOLOR
_FLICKERBASEMESSAGE.oneofs_by_name['payload'].fields.append(
  _FLICKERBASEMESSAGE.fields_by_name['strobe'])
_FLICKERBASEMESSAGE.fields_by_name['strobe'].containing_oneof = _FLICKERBASEMESSAGE.oneofs_by_name['payload']
_FLICKERBASEMESSAGE.oneofs_by_name['payload'].fields.append(
  _FLICKERBASEMESSAGE.fields_by_name['fade'])
_FLICKERBASEMESSAGE.fields_by_name['fade'].containing_oneof = _FLICKERBASEMESSAGE.oneofs_by_name['payload']
_FLICKERBASEMESSAGE.oneofs_by_name['payload'].fields.append(
  _FLICKERBASEMESSAGE.fields_by_name['setColor'])
_FLICKERBASEMESSAGE.fields_by_name['setColor'].containing_oneof = _FLICKERBASEMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Strobe'] = _STROBE
DESCRIPTOR.message_types_by_name['Fade'] = _FADE
DESCRIPTOR.message_types_by_name['SetColor'] = _SETCOLOR
DESCRIPTOR.message_types_by_name['FlickerBaseMessage'] = _FLICKERBASEMESSAGE

Strobe = _reflection.GeneratedProtocolMessageType('Strobe', (_message.Message,), dict(
  DESCRIPTOR = _STROBE,
  __module__ = 'flicker_base_message_pb2'
  # @@protoc_insertion_point(class_scope:Strobe)
  ))
_sym_db.RegisterMessage(Strobe)

Fade = _reflection.GeneratedProtocolMessageType('Fade', (_message.Message,), dict(
  DESCRIPTOR = _FADE,
  __module__ = 'flicker_base_message_pb2'
  # @@protoc_insertion_point(class_scope:Fade)
  ))
_sym_db.RegisterMessage(Fade)

SetColor = _reflection.GeneratedProtocolMessageType('SetColor', (_message.Message,), dict(
  DESCRIPTOR = _SETCOLOR,
  __module__ = 'flicker_base_message_pb2'
  # @@protoc_insertion_point(class_scope:SetColor)
  ))
_sym_db.RegisterMessage(SetColor)

FlickerBaseMessage = _reflection.GeneratedProtocolMessageType('FlickerBaseMessage', (_message.Message,), dict(
  DESCRIPTOR = _FLICKERBASEMESSAGE,
  __module__ = 'flicker_base_message_pb2'
  # @@protoc_insertion_point(class_scope:FlickerBaseMessage)
  ))
_sym_db.RegisterMessage(FlickerBaseMessage)


# @@protoc_insertion_point(module_scope)
